version: '3'
services:
        web:
                image: flask_jagger_v1
                build: .
                ports:
                        - "8087:8080"
                volumes:
                        - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/thewhitehouse/volumes
